services:
  backend:
    image: ghcr.io/fmatar/dungeon-flow:latest
    restart: unless-stopped

  frontend:
    image: ghcr.io/fmatar/dungeon-flow-ui:latest
    ports:
      - "80:80"
      - "5173:80" # Map 5173 to support local dev port expectations
    depends_on:
      - backend
    restart: unless-stopped
